[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
chat_app = "Fpzs4jNVnEV6seL2LGgmgiACSBbbuo5iyKJCBD7CEUZo"

[programs.localnet]
chat_app = "Fpzs4jNVnEV6seL2LGgmgiACSBbbuo5iyKJCBD7CEUZo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
